include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: juliagpu/cuda:10.1-cudnn7-cutensor1-devel-ubuntu18.04

.ltstest:
  extends:
    - .test
  script:
    - julia --project -e 'using Pkg; v"1.0" <= VERSION < v"1.2" && Pkg.add(PackageSpec(name="MbedTLS", version="0.6.8")) ; Pkg.build(); Pkg.test(; coverage=true)';

julia:1.1:
  extends:
    - .julia:1.1
    - .ltstest
  tags:
    - nvidia
    
julia:1.2:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia

julia:1.3:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia
  allow_failure: true

julia:nightly:
  extends:
    - .julia:nightly
    - .test
  tags:
    - nvidia
  allow_failure: true

coverage:
    extends:
    - .julia:1.2
    - .coverage
